### ISSUE TITLE
The url for the trash patch should be updated

### ISSUE THREAD

**Issue by blacksails** [sgeb/homebrew-mutt#2]
The following is taken from the official formula and works. There might be some of the other options which should be updated as well if you want it to reflect the official formula.

``` ruby
patch do
    url "ftp://ftp.openbsd.org/pub/OpenBSD/distfiles/mutt/trashfolder-1.5.22.diff0.gz"
    sha1 "c597566c26e270b99c6f57e046512a663d2f415e"
end if build.with? "trash-patch"
```

In any case thanks. I installed mutt with the sidebar patch using your formula.

**Comment by sgeb** [comment]
Fixed by PR #4.
