### ISSUE TITLE
patch-tracker.debian.org does not exist anymore

### ISSUE THREAD

**Issue by schoeke** [sgeb/homebrew-mutt#3]
==> Downloading http://patch-tracker.debian.org/patch/series/dl/mutt/1.5.21-6.2+deb7u1/features-old/patch-1.5.4.vk.pgp_verbose_mime

curl: (6) Could not resolve host: patch-tracker.debian.org
Error: Failed to download resource "mutt--patch"

**Comment by sgeb** [comment]
Fixed by 4504df1: "Update to mutt v1.6.1 (latest), test patches on travis-ci"

All tests are green: https://travis-ci.org/sgeb/homebrew-mutt/builds/142029992
Closing this issue, thanks for reporting! 👍
(and sorry for the late delay)
