### ISSUE TITLE
Sidebar patch fo mutt 1.5.24 is available now.

### ISSUE THREAD

**Issue by ghost** [sgeb/homebrew-mutt#6]
Hey, sidebar patch for mutt 1.5.24 is available for a while now. Could you please update your formula?

**Comment by sgeb** [comment]
Thanks for reporting and sorry for the delay. I will look into it.

**Comment by sgeb** [comment]
Fixed by 4504df1: "Update to mutt v1.6.1 (latest), test patches on travis-ci"

All tests are green: https://travis-ci.org/sgeb/homebrew-mutt/builds/142029992
Closing this issue, thanks for reporting! 👍
