### ISSUE TITLE
When's the last time you tested this?

### ISSUE THREAD

**Issue by geekpete** [sgeb/homebrew-mutt#7]

**Comment by sgeb** [comment]
I haven't been using this formula for some time. I assume you're asking since you've had an issue? If so, please provide more details and I'll try to look into it. Thanks.

**Comment by sgeb** [comment]
4504df1: "Update to mutt v1.6.1 (latest), test patches on travis-ci"
All tests are green: https://travis-ci.org/sgeb/homebrew-mutt/builds/142029992

I assume this fixes the problems you might be having with this tap.
Closing this issue.

**Comment by geekpete** [comment]
Works a treat now, thanks!
